import { SummaryMetric, RiskAlert, RiskInsight, ActionLog } from "./types";

export const summaryMetricsData: Omit<SummaryMetric, "icon">[] = [
  {
    title: "Total Risks",
    value: 156,
    trend: "+18%",
    trendDirection: "up",
    description: "All identified risks across India",
    color: "blue"
  },
  {
    title: "Active Alerts",
    value: 89,
    trend: "+12",
    trendDirection: "up",
    description: "Ongoing alerts requiring action",
    color: "red"
  },
  {
    title: "Critical Severity",
    value: 28,
    trend: "-3%",
    trendDirection: "down",
    description: "High priority alerts (%)",
    color: "orange"
  },
  {
    title: "Resolved Alerts",
    value: 92,
    trend: "+22%",
    trendDirection: "up",
    description: "Successfully mitigated issues (%)",
    color: "green"
  },
  {
    title: "Avg Response Time",
    value: "3.8h",
    trend: "-1.2h",
    trendDirection: "down",
    description: "Mean time to respond nationwide",
    color: "purple"
  }
];

export const alertsData: RiskAlert[] = [
  {
    id: "TN-A101",
    title: "Industrial Textile Dye Contamination - Coimbatore",
    type: "Industrial",
    category: "Environment",
    severity: "critical",
    source: "HMPI Engine",
    detectedOn: "09 Nov 2025",
    region: "Tamil Nadu",
    district: "Coimbatore",
    status: "active",
    hmpi: 84.2,
    contaminant: "Chromium, Azo Dyes, Heavy Metals",
    population: "3.5M",
    lastUpdated: "1 hour ago",
    assignedTo: "TN Pollution Control Board",
    actionTaken: "Emergency response team deployed",
    confidence: 96,
    coordinates: { lat: 11.0168, lng: 76.9558 },
    priority: 1
  },
  {
    id: "TN-A102",
    title: "Groundwater Depletion Alert - Madurai",
    type: "Environmental",
    category: "Water Scarcity",
    severity: "critical",
    source: "Satellite Monitoring",
    detectedOn: "08 Nov 2025",
    region: "Tamil Nadu",
    district: "Madurai",
    status: "active",
    hmpi: 78.9,
    contaminant: "Fluoride, TDS Elevation",
    population: "1.8M",
    lastUpdated: "3 hours ago",
    assignedTo: "TN Water Resources Dept",
    actionTaken: "Bore well restrictions imposed",
    confidence: 91,
    coordinates: { lat: 9.9252, lng: 78.1198 },
    priority: 1
  },
  {
    id: "TN-A103",
    title: "Salt Water Intrusion - Coastal Chennai",
    type: "Environmental",
    category: "Salinity",
    severity: "critical",
    source: "Coastal Monitoring System",
    detectedOn: "07 Nov 2025",
    region: "Tamil Nadu",
    district: "Chennai",
    status: "in-review",
    hmpi: 72.4,
    contaminant: "Chlorides, Sodium",
    population: "7.2M",
    lastUpdated: "6 hours ago",
    assignedTo: "Chennai Metro Water",
    actionTaken: "Reverse osmosis plants activated",
    confidence: 89,
    coordinates: { lat: 13.0827, lng: 80.2707 },
    priority: 1
  },
  {
    id: "TN-A104",
    title: "Agricultural Pesticide Runoff - Erode",
    type: "Agricultural",
    category: "Chemical Contamination",
    severity: "moderate",
    source: "Field Report",
    detectedOn: "06 Nov 2025",
    region: "Tamil Nadu",
    district: "Erode",
    status: "active",
    hmpi: 61.7,
    contaminant: "Organophosphates, Nitrates",
    population: "2.3M",
    lastUpdated: "12 hours ago",
    assignedTo: "Agricultural Extension Office",
    actionTaken: "Farmer awareness program initiated",
    confidence: 83,
    coordinates: { lat: 11.3410, lng: 77.7172 },
    priority: 1
  },
  {
    id: "MH-A201",
    title: "Chemical Plant Leak - Chhatrapati Sambhajinagar",
    type: "Industrial",
    category: "Chemical Hazard",
    severity: "critical",
    source: "Emergency Response",
    detectedOn: "09 Nov 2025",
    region: "Maharashtra",
    district: "Chhatrapati Sambhajinagar",
    status: "active",
    hmpi: 79.6,
    contaminant: "Benzene, Toluene, Xylene",
    population: "1.9M",
    lastUpdated: "2 hours ago",
    assignedTo: "Maharashtra PCB",
    actionTaken: "Plant sealed, evacuation initiated",
    confidence: 93,
    coordinates: { lat: 19.8762, lng: 75.3433 },
    priority: 2
  },
  {
    id: "MH-A202",
    title: "Sugar Mill Effluent - Kolhapur",
    type: "Industrial",
    category: "Organic Pollution",
    severity: "moderate",
    source: "Water Quality Test",
    detectedOn: "08 Nov 2025",
    region: "Maharashtra",
    district: "Kolhapur",
    status: "active",
    hmpi: 58.4,
    contaminant: "BOD, COD, Suspended Solids",
    population: "1.2M",
    lastUpdated: "8 hours ago",
    assignedTo: "Sugar Development Board MH",
    actionTaken: "Treatment plant upgrade ordered",
    confidence: 85,
    coordinates: { lat: 16.7050, lng: 74.2433 },
    priority: 2
  },
  {
    id: "MH-A203",
    title: "Mining Runoff - Nagpur",
    type: "Mining",
    category: "Heavy Metals",
    severity: "moderate",
    source: "Field Monitoring",
    detectedOn: "07 Nov 2025",
    region: "Maharashtra",
    district: "Nagpur",
    status: "in-review",
    hmpi: 52.8,
    contaminant: "Iron Ore, Manganese",
    population: "2.4M",
    lastUpdated: "1 day ago",
    assignedTo: "Mining Department MH",
    actionTaken: "Environmental audit initiated",
    confidence: 78,
    coordinates: { lat: 21.1458, lng: 79.0882 },
    priority: 2
  },
  {
    id: "KL-A301",
    title: "Coastal Erosion Impact - Kochi",
    type: "Environmental",
    category: "Coastal Vulnerability",
    severity: "critical",
    source: "Coastal Monitoring",
    detectedOn: "08 Nov 2025",
    region: "Kerala",
    district: "Ernakulam",
    status: "active",
    hmpi: 68.3,
    contaminant: "Saltwater, Sediment Load",
    population: "2.1M",
    lastUpdated: "4 hours ago",
    assignedTo: "Kerala Coastal Zone Board",
    actionTaken: "Sea wall construction approved",
    confidence: 87,
    coordinates: { lat: 9.9312, lng: 76.2673 },
    priority: 2
  },
  {
    id: "KL-A302",
    title: "Spice Processing Waste - Kozhikode",
    type: "Industrial",
    category: "Organic Waste",
    severity: "moderate",
    source: "Industry Inspection",
    detectedOn: "06 Nov 2025",
    region: "Kerala",
    district: "Kozhikode",
    status: "active",
    hmpi: 45.7,
    contaminant: "Organic Acids, Phenols",
    population: "1.1M",
    lastUpdated: "1 day ago",
    assignedTo: "Spice Board Kerala",
    actionTaken: "Waste treatment guidelines issued",
    confidence: 74,
    coordinates: { lat: 11.2588, lng: 75.7804 },
    priority: 2
  },
  {
    id: "KA-A401",
    title: "IT Park Groundwater Depletion - Bangalore",
    type: "Urban",
    category: "Water Scarcity",
    severity: "critical",
    source: "Urban Monitoring",
    detectedOn: "08 Nov 2025",
    region: "Karnataka",
    district: "Bangalore Urban",
    status: "active",
    hmpi: 71.2,
    contaminant: "Over-extraction, TDS Rise",
    population: "12.3M",
    lastUpdated: "5 hours ago",
    assignedTo: "BWSSB",
    actionTaken: "Bore well licensing suspended",
    confidence: 90,
    coordinates: { lat: 12.9716, lng: 77.5946 },
    priority: 2
  },
  {
    id: "KA-A402",
    title: "Coffee Processing Waste - Chikmagalur",
    type: "Agricultural",
    category: "Organic Pollution",
    severity: "moderate",
    source: "Agricultural Survey",
    detectedOn: "05 Nov 2025",
    region: "Karnataka",
    district: "Chikmagalur",
    status: "active",
    hmpi: 44.9,
    contaminant: "Coffee Pulp, Organic Matter",
    population: "1.2M",
    lastUpdated: "2 days ago",
    assignedTo: "Coffee Board Karnataka",
    actionTaken: "Composting facilities established",
    confidence: 72,
    coordinates: { lat: 13.3161, lng: 75.7720 },
    priority: 2
  },
  {
    id: "AP-A501",
    title: "Aquaculture Chemical Runoff - Guntur",
    type: "Aquaculture",
    category: "Chemical Contamination",
    severity: "moderate",
    source: "Water Quality Survey",
    detectedOn: "07 Nov 2025",
    region: "Andhra Pradesh",
    district: "Guntur",
    status: "active",
    hmpi: 56.8,
    contaminant: "Antibiotics, Feed Chemicals",
    population: "4.9M",
    lastUpdated: "10 hours ago",
    assignedTo: "AP Fisheries Department",
    actionTaken: "Best practices training initiated",
    confidence: 81,
    coordinates: { lat: 16.3067, lng: 80.4365 },
    priority: 3
  },
  {
    id: "AP-A502",
    title: "Pharmaceutical Waste - Hyderabad",
    type: "Industrial",
    category: "Pharmaceutical Pollution",
    severity: "critical",
    source: "Industrial Audit",
    detectedOn: "06 Nov 2025",
    region: "Andhra Pradesh",
    district: "Hyderabad",
    status: "in-review",
    hmpi: 69.4,
    contaminant: "Active Pharmaceutical Ingredients",
    population: "6.9M",
    lastUpdated: "14 hours ago",
    assignedTo: "AP Pollution Control Board",
    actionTaken: "Pharmaceutical cluster review",
    confidence: 88,
    coordinates: { lat: 17.3850, lng: 78.4867 },
    priority: 3
  },
  {
    id: "GJ-A601",
    title: "Chemical Industrial Cluster - Vadodara",
    type: "Industrial",
    category: "Multi-Chemical",
    severity: "critical",
    source: "Industrial Monitoring",
    detectedOn: "07 Nov 2025",
    region: "Gujarat",
    district: "Vadodara",
    status: "active",
    hmpi: 73.8,
    contaminant: "Mixed Industrial Chemicals",
    population: "2.1M",
    lastUpdated: "7 hours ago",
    assignedTo: "Gujarat PCB",
    actionTaken: "Cluster-wide inspection ordered",
    confidence: 91,
    coordinates: { lat: 22.3072, lng: 73.1812 },
    priority: 3
  },
  {
    id: "GJ-A602",
    title: "Salt Pan Brine Leakage - Kutch",
    type: "Industrial",
    category: "Salinity",
    severity: "moderate",
    source: "Satellite Detection",
    detectedOn: "04 Nov 2025",
    region: "Gujarat",
    district: "Kutch",
    status: "active",
    hmpi: 47.3,
    contaminant: "High Salinity Brine",
    population: "2.1M",
    lastUpdated: "3 days ago",
    assignedTo: "Salt Department Gujarat",
    actionTaken: "Containment barriers erected",
    confidence: 75,
    coordinates: { lat: 23.7337, lng: 69.8597 },
    priority: 3
  },
  {
    id: "WB-A701",
    title: "Jute Mill Effluent - Hooghly",
    type: "Industrial",
    category: "Organic Pollution",
    severity: "moderate",
    source: "River Monitoring",
    detectedOn: "05 Nov 2025",
    region: "West Bengal",
    district: "Hooghly",
    status: "active",
    hmpi: 51.6,
    contaminant: "Lignin, Organic Acids",
    population: "5.5M",
    lastUpdated: "2 days ago",
    assignedTo: "WB Jute Board",
    actionTaken: "Effluent treatment mandated",
    confidence: 79,
    coordinates: { lat: 22.9068, lng: 88.4069 },
    priority: 3
  },
  {
    id: "OD-A801",
    title: "Steel Plant Contamination - Rourkela",
    type: "Industrial",
    category: "Heavy Industry",
    severity: "moderate",
    source: "Industrial Monitoring",
    detectedOn: "04 Nov 2025",
    region: "Odisha",
    district: "Sundargarh",
    status: "active",
    hmpi: 49.2,
    contaminant: "Iron, Heavy Metals",
    population: "4.6M",
    lastUpdated: "3 days ago",
    assignedTo: "Odisha PCB",
    actionTaken: "Steel plant compliance review",
    confidence: 76,
    coordinates: { lat: 22.2604, lng: 84.8536 },
    priority: 3
  }
];

export const riskInsightsData: Omit<RiskInsight, "icon">[] = [
  {
    title: "🚨 CRITICAL: Coimbatore Industrial Crisis",
    description: "Tamil Nadu's textile hub showing HMPI 84.2 - National highest. 12 units shut down. Groundwater emergency declared.",
    priority: "high",
    region: "Tamil Nadu"
  },
  {
    title: "Multi-State Industrial Pattern",
    description: "Maharashtra (Chhatrapati Sambhajinagar), Gujarat (Vadodara), AP (Hyderabad) showing synchronized chemical contamination surge.",
    priority: "high",
    region: "Multi-State"
  },
  {
    title: "Coastal Vulnerability Corridor",
    description: "Tamil Nadu (Chennai) and Kerala (Kochi) coastal areas experiencing accelerated saltwater intrusion.",
    priority: "high",
    region: "Coastal States"
  },
  {
    title: "Southern IT Hub Water Crisis",
    description: "Bangalore and Chennai IT corridors showing critical groundwater depletion. 25M+ population at risk.",
    priority: "high",
    region: "South India"
  },
  {
    title: "Industrial Cluster Contamination",
    description: "Chemical industrial clusters in Gujarat, Maharashtra, and AP require immediate coordinated response.",
    priority: "medium",
    region: "Industrial States"
  }
];

export const actionLogsData: ActionLog[] = [
  {
    id: "TN-A101",
    action: "Emergency shutdown of 12 textile units in Coimbatore industrial zone",
    assignedTo: "Dr. Radhika Menon, TN Pollution Control Board",
    timestamp: "1 hour ago",
    status: "in-progress"
  },
  {
    id: "TN-A102",
    action: "Bore well moratorium implemented across Madurai district",
    assignedTo: "Collector Madurai, Water Resources Dept",
    timestamp: "3 hours ago",
    status: "completed"
  },
  {
    id: "TN-A103",
    action: "Activated 15 reverse osmosis plants for Chennai coastal areas",
    assignedTo: "Chennai Metro Water Board",
    timestamp: "6 hours ago",
    status: "completed"
  },
  {
    id: "TN-A104",
    action: "Farmer training program launched in Erode - sustainable practices",
    assignedTo: "Agricultural Extension Officer Erode",
    timestamp: "12 hours ago",
    status: "in-progress"
  },
  {
    id: "TN-A105",
    action: "Vellore tanneries: Upgraded effluent treatment to Zero Liquid Discharge",
    assignedTo: "Leather Development Board TN",
    timestamp: "1 day ago",
    status: "completed"
  }
];
