import type { Dataset } from './types';

export const datasets: Dataset[] = [
  {
    id: "DS001",
    title: "Ground Water Level Monitoring (CGWB)",
    description: "Water-level time series tables; links to WIMS. Download historical water levels and documentation; telemetry data handled via WIMS.",
    type: "Government",
    source: "CGWB",
    size: "N/A",
    format: ["Tables", "WIMS"],
    updated: "2024",
    available: true,
    category: "government",
    url: "https://cgwb.gov.in/en/ground-water-level-monitoring"
  },
  {
    id: "DS002",
    title: "Ground Water Data Access",
    description: "Redirect to India-WRIS groundwater module. Use WRIS to query and export groundwater level data for CGWB stations.",
    type: "Government",
    source: "CGWB → India-WRIS",
    size: "N/A",
    format: ["Web Portal"],
    updated: "2024",
    available: true,
    category: "government",
    url: "https://cgwb.gov.in/old_website/GW-data-access.html"
  },
  {
    id: "DS003",
    title: "Freeware for Groundwater Data Analysis",
    description: "Standalone Windows tools for analysis, not for data fetch; can complement your dashboard tools section.",
    type: "Software",
    source: "CGWB",
    size: "Various",
    format: ["Windows Executable"],
    updated: "2024",
    available: true,
    category: "government",
    url: "https://cgwb.gov.in/en/freewares-groundwater-data-analysis"
  },
  {
    id: "DS004",
    title: "India-WRIS WebGIS",
    description: "WebGIS with CSV/Excel downloads; GIS layers. Provides groundwater level, aquifer maps, and 130+ layers via interactive interface and downloads.",
    type: "Government",
    source: "India-WRIS",
    size: "Large",
    format: ["CSV", "Excel", "GIS"],
    updated: "2024",
    available: true,
    category: "government",
    url: "https://indiawris.gov.in/wris/"
  },
  {
    id: "DS005",
    title: "WRIS Description & Documentation",
    description: "Documentation mentioning telemetry modules and automatic report generation for WRIS.",
    type: "Documentation",
    source: "India-WRIS / CWC",
    size: "N/A",
    format: ["Web Page"],
    updated: "2024",
    available: true,
    category: "government",
    url: "https://www.cwc.gov.in/en/water-resources-information-system-wris"
  },
  {
    id: "DS006",
    title: "NWIC Water Data",
    description: "Portal for water-related datasets. Entry point for WRIS/WIMS-related data; access details vary by module.",
    type: "Government",
    source: "NWIC",
    size: "Various",
    format: ["Portal"],
    updated: "2024",
    available: true,
    category: "government",
    url: "https://nwic.gov.in/data"
  },
  {
    id: "DS007",
    title: "IN-GRES GEC Dashboard",
    description: "Web dashboard for groundwater resource assessment outputs. Useful for derived indicators and visualisations related to groundwater resources.",
    type: "Dashboard",
    source: "IN-GRES",
    size: "N/A",
    format: ["Web Dashboard"],
    updated: "2024",
    available: true,
    category: "academic",
    url: "https://ingres.iith.ac.in"
  },
  {
    id: "DS008",
    title: "CPCB NWMP Water Quality Data",
    description: "Excel/CSV downloads for water quality. Use for surface water and some groundwater quality time series, station-wise.",
    type: "Government",
    source: "CPCB",
    size: "Various",
    format: ["Excel", "CSV"],
    updated: "2024",
    available: true,
    category: "government",
    url: "https://cpcb.nic.in/nwmp-data/"
  },
  {
    id: "DS009",
    title: "Surface Water Quality March 2021",
    description: "Example of CPCB dataset on OGD; check each resource for API status.",
    type: "Government",
    source: "CPCB via OGD",
    size: "Various",
    format: ["CSV"],
    updated: "2021",
    available: true,
    category: "government",
    url: "https://www.data.gov.in/resource/surface-water-quality-march-2021-cpcb"
  },
  {
    id: "DS010",
    title: "Ground Water Quality Stations Shapefile",
    description: "Gives station locations and attributes for all groundwater quality stations across India.",
    type: "Geospatial",
    source: "Multi-agency",
    size: "ZIP",
    format: ["Shapefile", "SHP", "DBF"],
    updated: "2024",
    available: true,
    category: "government",
    url: "https://www.data.gov.in/resource/shape-file-ground-water-quality-stations"
  }
];
